### ISSUE TITLE
on Hyper v 3.0.0 looks weird

### ISSUE THREAD

**Issue by IgorMuzyka** [hummal/hyper-monokai-deluxe#3] opened 2019-05-06 21:08 UTC
<img width="780" alt="Screen Shot 2019-05-07 at 00 07 08" src="https://user-images.githubusercontent.com/4402333/57255310-1e599400-705c-11e9-8d77-8294d6a90596.png">

**Comment by philipp-winterle** [comment] 2019-05-10 09:02
Hey Igor,

I checked the latest version (3.0.2) of hyper with hyper-monokai-deluxe and it looks like it should.
Maybe some other plugins not working as expected? 
What is your config?

![hyper](https://user-images.githubusercontent.com/633711/57515526-2727bf80-7313-11e9-9d14-6a507464e14f.png)

**Comment by IgorMuzyka** [comment] 2019-05-12 00:06
here is a list of my hyper plugins 
```js
    "hyperminimal",
    "hyperterm-cursor",
    "hyperterm-paste",
    "hyper-search",
    "hyper-monokai-deluxe"
```

**Comment by travVT** [comment] 2019-05-23 13:52
I'm getting the same thing with Hyper 3.0.2 on my Mac. If I uninstall and reinstall the plugin it looks okay until the next time I open Hyper. Any ideas? Thanks! :)

**Comment by philipp-winterle** [comment] 2019-05-23 14:03
I was able to reproduce it now. Seems to have something to do with OSX strategy of displaying motion blur. Will have a closer look if I can do something or if its a hyper.js issue

**Comment by philipp-winterle** [comment] 2019-05-24 13:17
Fixed in 1.0.5

Try the new option "theme" with value "reloaded" for a better css layout

Thank your for reporting

**Closed as completed by philipp-winterle** 2019-05-24 13:17 UTC
Labels: bug

**Comment by travVT** [comment] 2019-05-28 17:16
Thanks @hummal, it's working great now! :)
